#include "token.h"

static const char *KIND_NAMES[TOK_COUNT] = {
    [TOK_PACKAGE]   = "package",
    [TOK_IMPORT]    = "import",
    [TOK_PUB]       = "pub",
    [TOK_FN]        = "fn",
    [TOK_LET]       = "let",
    [TOK_CONST]     = "const",
    [TOK_RETURN]    = "return",
    [TOK_IF]        = "if",
    [TOK_ELSE]      = "else",
    [TOK_WHILE]     = "while",
    [TOK_LOOP]      = "loop",
    [TOK_BREAK]     = "break",
    [TOK_CONTINUE]  = "continue",
    [TOK_STRUCT]    = "struct",
    [TOK_ENUM]      = "enum",
    [TOK_UNION]     = "union",
    [TOK_INTERFACE] = "interface",
    [TOK_IMPL]      = "impl",
    [TOK_UNSAFE]    = "unsafe",
    [TOK_EXTERN]    = "extern",
    [TOK_AS]        = "as",
    [TOK_MATCH]     = "match",
    [TOK_KERNEL]    = "kernel",
    [TOK_NATIVE]    = "native",
    [TOK_UI]        = "ui",
    [TOK_ANDROID]   = "android",
    [TOK_DRIVER]    = "driver",
    [TOK_APP]       = "app",
    [TOK_MODULE]    = "module",
    [TOK_DEFER]     = "defer",
    [TOK_COMPTIME]  = "comptime",
    [TOK_TRUE]      = "true",
    [TOK_FALSE]     = "false",
    [TOK_NULL]      = "null",
    [TOK_SELF]        = "Self",
    [TOK_UNDERSCORE]  = "_",
    [TOK_IDENT]     = "IDENT",
    [TOK_INT]       = "INT",
    [TOK_FLOAT]     = "FLOAT",
    [TOK_STRING]    = "STRING",
    [TOK_CHAR]      = "CHAR",
    [TOK_LBRACE]    = "{",
    [TOK_RBRACE]    = "}",
    [TOK_LPAREN]    = "(",
    [TOK_RPAREN]    = ")",
    [TOK_LBRACKET]  = "[",
    [TOK_RBRACKET]  = "]",
    [TOK_SEMICOLON] = ";",
    [TOK_COLON]     = ":",
    [TOK_COMMA]     = ",",
    [TOK_DOT]       = ".",
    [TOK_ARROW]     = "->",
    [TOK_FAT_ARROW] = "=>",
    [TOK_EQ]        = "=",
    [TOK_EQEQ]      = "==",
    [TOK_NE]        = "!=",
    [TOK_LT]        = "<",
    [TOK_LE]        = "<=",
    [TOK_GT]        = ">",
    [TOK_GE]        = ">=",
    [TOK_PLUS]      = "+",
    [TOK_MINUS]     = "-",
    [TOK_STAR]      = "*",
    [TOK_SLASH]     = "/",
    [TOK_PERCENT]   = "%",
    [TOK_AMP]       = "&",
    [TOK_ANDAND]    = "&&",
    [TOK_PIPE]      = "|",
    [TOK_OROR]      = "||",
    [TOK_CARET]     = "^",
    [TOK_TILDE]     = "~",
    [TOK_BANG]      = "!",
    [TOK_QUESTION]  = "?",
    [TOK_AT]        = "@",
    [TOK_PLUS_EQ]    = "+=",
    [TOK_MINUS_EQ]   = "-=",
    [TOK_STAR_EQ]    = "*=",
    [TOK_SLASH_EQ]   = "/=",
    [TOK_PERCENT_EQ] = "%=",
    [TOK_EOF]       = "EOF",
};

const char *token_kind_name(TokenKind kind) {
    if (kind < 0 || kind >= TOK_COUNT) return "UNKNOWN";
    return KIND_NAMES[kind];
}
